version: "3.8"

services:
  web:
    build: .
    networks:
      - caddy_net

  caddy:
    image: caddy:2.4.5
    ports:
      - "3001:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
    depends_on:
      - web
    networks:
      - caddy_net

networks:
  caddy_net:
    external: false
