version: "3.8"

services:
  zipline_web:
    container_name: zipline_web
    build: .
    networks:
      - caddy_net
      - shared_network

  caddy:
    image: caddy:2.4.5
    container_name: zipline_caddy
    ports:
      - "3001:80"
    volumes:
      - ./caddy_files:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - zipline_web
    networks:
      - caddy_net
      - shared_network

networks:
  caddy_net:
    external: false
  shared_network:
    external: true

volumes:
  caddy_data:
  caddy_config:
