version: "3.8"

services:
  zipline_web:
    build: .
    networks:
      - caddy_net
      - shared_network

  caddy:
    build:
      context: .
      dockerfile: DockerfileCaddy
    ports:
      - "3001:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - zipline_web
    networks:
      - caddy_net
      - shared_network

networks:
  caddy_net:
    external: false
  shared_network:
    external: true

volumes:
  caddy_data:
  caddy_config:
