version: "3.8"

services:
  zipline_web:
    build: .
    networks:
      - caddy_net
      - shared_network

  caddy:
    image: caddy:2.4.5
    ports:
      - "3001:80"
    volumes:
      - ./caddy:/etc/caddy
      - ./data:/data
      - ./config:/config
    depends_on:
      - zipline_web
    networks:
      - caddy_net
      - shared_network

networks:
  caddy_net:
    external: false
  shared_network:
    external: true
